model_list:
  - model_name: gpt-4o-mini ### RECEIVED MODEL NAME ###
    litellm_params: # all params accepted by litellm.completion() - https://docs.litellm.ai/docs/completion/input
      model: openai/gpt-4o-mini ### MODEL NAME sent to `litellm.completion()` ###
      api_base: https://api.openai.com/v1/
      api_key: "os.environ/OPENAI_API_KEY" # does os.getenv("OPENAI_API_KEY")
      rpm: 10      # [OPTIONAL] Rate limit for this deployment: in requests per minute (rpm)
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_base: https://api.openai.com/v1/
      api_key: "os.environ/OPENAI_API_KEY"
      rpm: 10
  - model_name: text-embedding-3-small
    litellm_params:
      model: openai/text-embedding-3-small
      api_base: https://api.openai.com/v1/
      api_key: "os.environ/OPENAI_API_KEY"
      rpm: 10
  - model_name: Claude 3.5 Sonnet
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20240620
      api_base: https://api.anthropic.com
      api_key: "os.environ/ANTHROPIC_API_KEY"
      drop_params: true
      rpm: 10
  - model_name: Claude 3 Opus
    litellm_params:
      model: anthropic/claude-3-opus-20240229
      api_base: https://api.anthropic.com
      api_key: "os.environ/ANTHROPIC_API_KEY"
      drop_params: true
      rpm: 10
  - model_name: Claude 3.5 Haiku
    litellm_params:
      model: anthropic/claude-3-5-haiku-20241022
      api_base: https://api.anthropic.com
      api_key: "os.environ/ANTHROPIC_API_KEY"
      drop_params: true
      rpm: 10